MOCK_JOB = {
    "id": "1",
    "company_profile_id": "123",
    "company_name": "Tech Innovations Inc.",
    "role_name": "Software Engineer",
    "industry": ["Technology"],
    "weekly_hours": "40",
    "work_mode": "Remote",
    "location": "San Francisco, CA",
    "qualifications": ["Bachelor's degree in Computer Science or related field"],
    "accommodations": ["Wheelchair accessible office", "flexible work hours"],
    "application_period_start": "2023-10-01",
    "application_period_end": "2023-11-01",
    "application_status": "Open",
    "job_type": "Full-time",
    "application_materials": ["Resume", "Cover Letter"],
    "job_description": "We are looking for a skilled software engineer to join our team. The ideal candidate will have experience in full-stack development and a passion for building innovative solutions.",
    "application_link": "https://techinnovations.com/careers/apply",
    "created_at": "2023-09-01T12:00:00Z",
    "updated_at": "2023-09-15T12:00:00Z"
}

MOCK_USER_PROFILE = {
  "id": "456",
  "user_id": "789",
  "age_range": "25-34",
  "hours_per_week": "40",
  "location": "San Francisco, CA",
  "accommodations": ["Wheelchair accessible office", "Flexible work hours"],
  "educational_background": "Bachelor's degree in Computer Science",
  "remote_preference": True,
  "hybrid_preference": False,
  "in_person_preference": False,
  "created_at": "2023-09-01T12:00:00Z",
  "updated_at": "2023-09-15T12:00:00Z"
}

MOCK_RESPONSE = [{
    "id": "in-3f945b90058c1143",
    "site": "indeed",
    "job_url": "https://www.indeed.com/viewjob?jk=3f945b90058c1143",
    "job_url_direct": "https://careers-indeed.icims.com/jobs/46003/job",
    "title": "Software Engineer II - Full Stack",
    "company": "Indeed",
    "location": "New York, NY, US",
    "date_posted": 1751760000000,
    "job_type": "fulltime",
    "salary_source": "direct_data",
    "interval": "yearly",
    "min_amount": 134000,
    "max_amount": 194000,
    "currency": "USD",
    "is_remote": True,
    "job_level": None,
    "job_function": None,
    "listing_type": None,
    "emails": None,
    "description": "Our Mission: As the world’s number 1 job site, our mission is to help people get jobs. We strive to cultivate an inclusive and accessible workplace where all people feel comfortable being themselves. We're looking to grow our teams with more people who share our enthusiasm for innovation and creating the best experience for job seekers. Day to Day: Write software to fulfill both well-specified, small-scoped work requests and larger, less well defined work requests for your team's products. Work with Product Managers and other stakeholders to clarify requirements, decompose large requests into smaller ones that can be executed sequentially or in parallel, and refine and clarify Product and Engineering goals and ensure they align with company objectives. Help design new systems and enhancements to existing systems to support substantial new features and products. Write software to fix complex bugs, triage newly reported bugs by estimating scope and priority of each bug, investigate problems, and recommend fixes for your team’s products. Provide feedback within your team and to peers in the Engineering and Product organizations regarding code changes made by other engineers, designs for new enhancements, and what they are doing well or where they have opportunities for growth. Write documentation for your team’s products, code, and work items. Share your expertise on products and technologies by mentoring other engineers and helping them prioritize work items based on urgency, business impact, and goals. Help interview candidates for various positions in the Engineering organization, and participate in group discussions on candidates’ fitness for those positions. Position is in New York, NY. Up to 100% telecommuting from anywhere in the U.S. is permitted. Minimum Requirements: Bachelor’s or foreign equivalent degree in Computer Science, Computer Engineering, Electrical Engineering, Mathematics, or a closely related computer technical field; Two years of work experience in software programming, using at least one of the following languages: Kotlin, Java, Scala, C, C++, C#, Python, or Go;* Two years of work experience building web applications or services; Two years of work experience using 3-tier architecture with a focus on services and data stores; and One year of work experience developing software for distributed computing and distributed systems\n\nExperience may be gained concurrently. Benefits: - Health, Work/Life Harmony, Wellbeing  We care about what you care about. We have a multitude of benefits to support Indeedians, as well as their pets, kids, and partners including medical, dental, vision, disability and life insurance. Indeedians are able to enroll in our company’s 401k plan, as well as an equity-based incentive program. Indeedians will also receive open paid time off, 12 paid holidays a year and up to 26 weeks of paid parental leave. For more information, select your country and learn more about our employee benefits, program, \\& perks at https://www.indeed.com/careers/benefits! Equal Opportunities and Accommodations Statement: Indeed is deeply committed to building a workplace and global community where inclusion is not only valued, but prioritized. We’re proud to be an Equal Employment and Affirmative Action employer seeking to create a welcoming and inclusive environment. All qualified applicants will receive consideration for employment without regard to disability, status as a protected veteran, or any other non\\-merit based or legally protected grounds. Indeed is dedicated to providing reasonable accommodations to qualified individuals with known disabilities to participate in the employment application process. To learn more about requesting an accommodation, please visit https://www.indeed.com/careers/accommodations. In the request for an accommodation, please inform us of the nature of your request and your contact information. If you are requesting accommodation for an interview, please reach out at least one week in advance of your interview. For more information about our commitment to equal opportunity/affirmative action, please visit our ESG home page (https://www.indeed.com/esg?co=US).",
    "company_industry": "technology",
    "company_url": "https://www.indeed.com/cmp/Indeed",
    "company_logo": "https://d2q79iu7y748jz.cloudfront.net/s/_squarelogo/256x256/ff794fb897747bee7ebc1325d4b7a7da",
    "company_url_direct": "https://www.indeed.com",
    "company_addresses": "Austin, TX",
    "company_num_employees": "10,000+",
    "company_revenue": "$1B to $5B (USD)",
    "company_description": "We help people get jobs.",
    "skills": None,
    "experience_range": None,
    "company_rating": None,
    "company_reviews_count": None,
    "vacancy_count": None,
    "work_from_home_type": None
  },
  {
    "id": "li-4259594855",
    "site": "linkedin",
    "job_url": "https://www.linkedin.com/jobs/view/4259594855",
    "job_url_direct": None,
    "title": "Software Engineer, Backend",
    "company": "Tinder",
    "location": "Palo Alto, CA",
    "date_posted": 1751414400000,
    "job_type": None,
    "salary_source": None,
    "interval": None,
    "min_amount": None,
    "max_amount": None,
    "currency": None,
    "is_remote": True,
    "job_level": "",
    "job_function": None,
    "listing_type": None,
    "emails": None,
    "description": "Launched in 2012, Tinder® revolutionized how people meet, growing from 1 match to one billion matches in just two years. This rapid growth demonstrates its ability to fulfill a fundamental human need: real connection. Today, the app has been downloaded over 630 million times, leading to over 97 billion matches, serving approximately 50 million users per month in 190 countries and 45+ languages - a scale unmatched by any other app in the category. In 2024, Tinder won four Effie Awards for its first-ever global brand campaign, “It Starts with a Swipe",
    "company_industry": None,
    "company_url": "https://www.linkedin.com/company/tinder-incorporated",
    "company_logo": None,
    "company_url_direct": None,
    "company_addresses": None,
    "company_num_employees": None,
    "company_revenue": None,
    "company_description": None,
    "skills": "Excellent knowledge and experience with a backend language like Java, Node.js, Go, C++, BS/MS in Computer Science or an equivalent field with 2+ years of industry work experience, Excellent knowledge of Computer Science fundamentals with strong competencies in data structures, algorithms, and coding, Strong designing and building distributed backend systems handling high volumes of traffic, Experience in handling ambiguous business requirements with excellent prioritization, time management abilities, and a focus on execution, Passion to tackle exciting engineering problems and make continuous improvements",
    "experience_range": None,
    "company_rating": None,
    "company_reviews_count": None,
    "vacancy_count": None,
    "work_from_home_type": None
  },
  {
    "id": "nk-300922500449",
    "site": "naukri",
    "job_url": "https://www.naukri.com/job-listings-senior-software-developer-c-net-sql-erp-software-index-infotech-india-pvt-ltd-pune-4-to-5-years-300922500449",
    "job_url_direct": None,
    "title": "Senior Software Developer (C#.net, SQL, ERP Software)",
    "company": "Index Infotech India",
    "location": "Pune, India",
    "date_posted": 1751463700000,
    "job_type": None,
    "salary_source": None,
    "interval": None,
    "min_amount": None,
    "max_amount": None,
    "currency": None,
    "is_remote": True,
    "job_level": None,
    "job_function": None,
    "listing_type": None,
    "emails": None,
    "description": "Index InfoTech is a leading business transformation and ERP consulting company, headquartered in Dubai, UAE and offices across the globe. We implement the world s 5 th largest ERP Epicor and build niche enterprise tech-products for our customers helping them leverage SaaS and on-premises technologies for their business growth.",
    "company_industry": None,
    "company_url": "https://www.naukri.com/index-infotech-india-jobs-careers-6141990",
    "company_logo": "https://img.naukimg.com/logo_images/groups/v1/7790199.gif",
    "company_url_direct": None,
    "company_addresses": None,
    "company_num_employees": None,
    "company_revenue": None,
    "company_description": None,
    "skills": "SAN, SAP, SAP CRM, SSRS, Data structures, Visual Studio, Oracle, microsoft",
    "experience_range": "4-5 Yrs",
    "company_rating": 3.5,
    "company_reviews_count": 10,
    "vacancy_count": None,
    "work_from_home_type": "Work from office"
  }]